module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 120],
    'scope-enum': [
      2,
      'always',
      [
        'admin',
        'analytics',
        'auth',
        'config',
        'dashboard',
        'deps',
        'docs',
        'hooks',
        'security',
        'settings',
        'tests',
        'theme',
        'users',
      ],
    ],
    'subject-case': [0],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
};
