import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  Sidebar: [
    {
      type: 'doc',
      label: 'Getting Started',
      id: 'getting-started',
    },
    {
      type: 'category',
      label: 'Configs',
      collapsible: true,
      collapsed: false,
      items: ['configs/ts-config', 'configs/vite-config', 'configs/vitest-config', 'configs/sentry-config'],
    },
    {
      type: 'category',
      label: 'GitLab Catalogs',
      collapsible: true,
      collapsed: false,
      items: ['ci'],
    },
  ],
}

export default sidebars
